language: cpp

matrix:
  fast_finish: true
  include:
    - os: osx
      env: CC_COMPILER=clang CXX_COMPILER=clang++

    - os: linux
      sudo: false
      env: CC_COMPILER=gcc CXX_COMPILER=g++

script:
  - $CC_COMPILER -v
  - $CXX_COMPILER -v
  - mkdir build
  - cd build
  - cmake ..
  - make

env:
  global:
  - LANG="en_US.UTF-8"
